services:

  epidemietrackr-back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
  #port du server : port de l'appliaction
      - 5091:8000
    volumes:
      - .:/epidemietrackr-app/
    environment:
      DATABASE_NAME: DATABASE_NAME
      DATABASE_USER: DATABASE_USER
      DATABASE_PASSWORD: DATABASE_PASSWORD
      DATABASE_HOST: DATABASE_HOST
      DATABASE_PORT: DATABASE_PORT
      DJANGO_SECRET_KEY: DJANGO_SECRET_KEY
      DJANGO_DEBUG: DJANGO_DEBUG
      DJANGO_ALLOWED_HOSTS: DJANGO_ALLOWED_HOSTS

    depends_on:
      - epidemietrackrDB


  epidemietrackrDB:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=$DATABASE_PASSWORD
      - POSTGRES_DB=$DATABASE_NAME
      - POSTGRES_USER=$DATABASE_USER
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DATABASE_USER" ]
      interval: 30s
      timeout: 10s
      retries: 5


  adminer:
    image: adminer
    restart: always

    ports:
      - 8080:8080

volumes:
  pgdata:
