# Generated by Django 4.2.15 on 2024-08-09 16:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.RenameField(
            model_name='historicalpatient',
            old_name='adresse',
            new_name='ville',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='adresse',
            new_name='ville',
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='commune',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='epidemie.commune'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidemie.commune'),
        ),
    ]
