# Generated by Django 4.2.15 on 2025-06-11 20:41

from django.db import migrations, models
import epidemie.models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='api_key',
            field=models.CharField(default=epidemie.models.generate_api_key, max_length=128, unique=True),
        ),
    ]
