# Generated by Django 4.2.15 on 2024-09-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0002_alter_historicalpatient_groupe_sanguin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('access_all', 'access all'), ('access_region', 'access region'), ('access_district', 'access district'), ('can_view_district', 'Can view district'), ('can_view_region', 'Can view region'), ('can_view_national', 'Can view national'), ('can_edit_employee', 'Can edit employee details'), ('can_delete_employee', 'Can delete employee'), ('can_assign_roles', 'Can assign roles to employees'))},
        ),
    ]
