# Generated by Django 4.2.15 on 2024-08-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0002_commune_rename_adresse_historicalpatient_ville_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='ville',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidemie.city', verbose_name='Ville'),
        ),
    ]
