# Generated by Django 4.2.15 on 2025-06-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0002_polesregionaux_alter_healthregion_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeepidemie',
            name='nom',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
