# Generated by Django 4.2.15 on 2024-08-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0003_commune_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='prelevemode',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
