# Generated by Django 4.2.15 on 2025-06-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0003_typeepidemie_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalementjournal',
            name='source_application',
            field=models.CharField(blank=True, help_text="Nom de l'application ayant envoyé le signalement.", max_length=100, null=True),
        ),
    ]
