# Generated by Django 4.2.15 on 2024-09-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0003_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('access_all', 'access all'), ('access_region', 'access region'), ('access_district', 'access district'), ('can_assign_roles', 'Can assign roles to employees'))},
        ),
    ]
