# Generated by Django 4.2.15 on 2024-08-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0004_prelevemode_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='code_patient',
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(blank=True, max_length=500, unique=True),
        ),
    ]
