# Generated by Django 4.2.15 on 2024-08-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0005_alter_historicalpatient_code_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='echantillon',
            name='resultat',
            field=models.CharField(blank=True, choices=[('POSITIF', 'POSITIF'), ('NEGATIF', 'NEGATIF')], default='NEGATIF', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalechantillon',
            name='resultat',
            field=models.CharField(blank=True, choices=[('POSITIF', 'POSITIF'), ('NEGATIF', 'NEGATIF')], default='NEGATIF', max_length=100, null=True),
        ),
    ]
