# Generated by Django 4.2.15 on 2024-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0006_echantillon_resultat_historicalechantillon_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatient',
            name='decede',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalpatient',
            name='gueris',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='decede',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='gueris',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='resultat',
            field=models.CharField(blank=True, choices=[('POSITIF', 'POSITIF'), ('NEGATIF', 'NEGATIF')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalechantillon',
            name='resultat',
            field=models.CharField(blank=True, choices=[('POSITIF', 'POSITIF'), ('NEGATIF', 'NEGATIF')], max_length=100, null=True),
        ),
    ]
