# Generated by Django 4.2.15 on 2024-08-10 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0007_historicalpatient_decede_historicalpatient_gueris_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtsanitaire',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epidemie.districtsanitaire'),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='code_patient',
            field=models.CharField(blank=True, db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(blank=True, max_length=225, unique=True),
        ),
    ]
