# Generated by Django 4.2.15 on 2024-08-10 18:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0008_districtsanitaire_nom_servicesanitaire_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesanitaire',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
