# Generated by Django 4.2.15 on 2024-08-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0009_servicesanitaire_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesanitaire',
            name='completeness',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='upstream',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesanitaire',
            name='what3words',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
