# Generated by Django 4.2.15 on 2024-08-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0011_commune_is_in_commune_name_en_commune_osm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='population',
            field=models.CharField(blank=True, null=True),
        ),
    ]
