# Generated by Django 4.2.15 on 2024-08-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0012_alter_commune_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
