# Generated by Django 4.2.15 on 2024-08-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0013_alter_commune_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='ville',
        ),
    ]
