# Generated by Django 4.2.15 on 2024-08-11 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0014_remove_commune_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='ville',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ville',
        ),
    ]
