# Generated by Django 4.2.15 on 2024-08-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0015_remove_historicalpatient_ville_remove_patient_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='date_naissance',
            field=models.DateField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='lieu_naissance',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
