# Generated by Django 4.2.15 on 2024-08-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0016_alter_historicalpatient_date_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
