# Generated by Django 4.2.15 on 2024-08-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0017_alter_historicalpatient_lieu_naissance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
