# Generated by Django 4.2.15 on 2024-08-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0018_alter_historicalpatient_date_naissance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epidemie',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to='epidemie/thumbnails'),
        ),
    ]
