# Generated by Django 4.2.15 on 2024-08-21 20:24

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0019_epidemie_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epidemie',
            name='symptômes',
        ),
        migrations.AddField(
            model_name='epidemie',
            name='symptomes',
            field=models.ManyToManyField(blank=True, null=True, related_name='épidémies', to='epidemie.symptom'),
        ),
        migrations.AlterField(
            model_name='epidemie',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='epidemie',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
