# Generated by Django 4.2.15 on 2024-08-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0021_alter_echantillon_code_echantillon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echantillons', to='epidemie.patient'),
        ),
    ]
