# Generated by Django 4.2.15 on 2024-08-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0022_alter_echantillon_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthregion',
            name='geom',
        ),
        migrations.AddField(
            model_name='districtsanitaire',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epidemie.healthregion'),
        ),
    ]
