# Generated by Django 4.2.15 on 2024-08-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0023_remove_healthregion_geom_districtsanitaire_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='epidemie.districtsanitaire'),
        ),
    ]
