# Generated by Django 4.2.15 on 2024-08-25 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0024_commune_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemie',
            name='symptomes',
            field=models.ManyToManyField(related_name='épidémies', to='epidemie.symptom'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='contact',
            field=models.CharField(blank=True, db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='genre',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nationalite',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nbr_enfants',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nom',
            field=models.CharField(blank=True, db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='prenoms',
            field=models.CharField(blank=True, db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('Celibataire', 'Celibataire'), ('Concubinage', 'Concubinage'), ('Marie', 'Marié'), ('Divorce', 'Divorcé'), ('Veuf', 'Veuf'), ('Autre', 'Autre')], db_index=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(blank=True, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='epidemie.employee'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationalite',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nbr_enfants',
            field=models.PositiveIntegerField(blank=True, default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(blank=True, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenoms',
            field=models.CharField(blank=True, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('Celibataire', 'Celibataire'), ('Concubinage', 'Concubinage'), ('Marie', 'Marié'), ('Divorce', 'Divorcé'), ('Veuf', 'Veuf'), ('Autre', 'Autre')], max_length=225, unique=True),
        ),
    ]
