# Generated by Django 4.2.15 on 2024-08-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0025_alter_epidemie_symptomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='genre',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nationalite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nbr_enfants',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='nom',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='prenoms',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('Celibataire', 'Celibataire'), ('Concubinage', 'Concubinage'), ('Marie', 'Marié'), ('Divorce', 'Divorcé'), ('Veuf', 'Veuf'), ('Autre', 'Autre')], max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='genre',
            field=models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationalite',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nbr_enfants',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenoms',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('Celibataire', 'Celibataire'), ('Concubinage', 'Concubinage'), ('Marie', 'Marié'), ('Divorce', 'Divorcé'), ('Veuf', 'Veuf'), ('Autre', 'Autre')], max_length=225),
        ),
    ]
