# Generated by Django 4.2.15 on 2024-08-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0026_alter_historicalpatient_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='contact',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
