# Generated by Django 4.2.15 on 2024-08-27 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0027_alter_historicalpatient_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemie',
            name='thumbnails',
            field=models.ImageField(blank=True, default='media/epidemie_thumbnails.png', null=True, upload_to='epidemie/thumbnails'),
        ),
    ]
