# Generated by Django 4.2.15 on 2024-08-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0028_alter_epidemie_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='resultat',
            field=models.CharField(blank=True, choices=[('POSITIF', 'POSITIF'), ('NEGATIF', 'NEGATIF')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='echantillon',
            name='site_collect',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalechantillon',
            name='resultat',
            field=models.CharField(blank=True, choices=[('POSITIF', 'POSITIF'), ('NEGATIF', 'NEGATIF')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='historicalechantillon',
            name='site_collect',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='code_patient',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=225),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='employeur',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='quartier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='code_patient',
            field=models.CharField(blank=True, editable=False, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='employeur',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='niveau_etude',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='quartier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
