# Generated by Django 4.2.15 on 2024-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0029_alter_echantillon_resultat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpatient',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
