# Generated by Django 4.2.15 on 2024-08-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0030_alter_historicalpatient_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantillon',
            name='code_echantillon',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalechantillon',
            name='code_echantillon',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
