# Generated by Django 4.2.15 on 2024-09-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0031_alter_echantillon_code_echantillon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemie',
            name='thumbnails',
            field=models.ImageField(blank=True, default='media/epidemie/epidemie_thumbnails.png', null=True, upload_to='epidemie/thumbnails'),
        ),
    ]
