# Generated by Django 4.2.15 on 2024-09-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0032_alter_epidemie_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epidemie',
            name='thumbnails',
            field=models.ImageField(blank=True, null=True, upload_to='epidemie/thumbnails'),
        ),
    ]
