# Generated by Django 4.2.15 on 2024-09-11 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0033_alter_epidemie_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='population',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='StructureProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='epidemie.districtsanitaire')),
            ],
        ),
        migrations.CreateModel(
            name='CasSynthese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_cas_suspects', models.IntegerField(default=0, help_text='Nombre de cas suspects.')),
                ('date_enregistrement', models.DateField(help_text="Date d'enregistrement des cas suspects.")),
                ('nom_prenoms_cas', models.CharField(blank=True, help_text='Nom et prénoms du cas suspect.', max_length=200, null=True)),
                ('age', models.IntegerField(blank=True, help_text='Âge du cas suspect.', null=True)),
                ('sexe', models.CharField(blank=True, choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=10, null=True)),
                ('cas_positif', models.BooleanField(default=False, help_text='Indique si le cas est positif.')),
                ('cas_negatif', models.BooleanField(default=False, help_text='Indique si le cas est négatif.')),
                ('evacue', models.BooleanField(default=False, help_text='Indique si le cas a été évacué.')),
                ('date_prelevement', models.DateField(blank=True, help_text='Date du prélèvement.', null=True)),
                ('decede', models.BooleanField(default=False, help_text='Indique si le cas est décédé.')),
                ('gueri', models.BooleanField(default=False, help_text='Indique si le cas est guéri.')),
                ('suivi_en_cours', models.BooleanField(default=True, help_text='Indique si le suivi est en cours.')),
                ('nbre_sujets_contacts', models.IntegerField(default=0, help_text='Nombre de sujets contacts.')),
                ('contacts_en_cours_suivi', models.IntegerField(default=0, help_text='Nombre de contacts en cours de suivi.')),
                ('contacts_sorti_suivi', models.IntegerField(default=0, help_text='Nombre de contacts sortis du suivi.')),
                ('devenu_suspect', models.IntegerField(default=0, help_text='Nombre de contacts devenus suspects.')),
                ('devenu_positif', models.IntegerField(default=0, help_text='Nombre de contacts devenus positifs.')),
                ('observations', models.TextField(blank=True, help_text='Observations sur le cas et son suivi.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_sanitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas', to='epidemie.districtsanitaire')),
                ('structure_provenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas', to='epidemie.structureprovenance')),
            ],
        ),
    ]
