# Generated by Django 4.2.15 on 2024-09-11 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0034_alter_commune_population_structureprovenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassynthese',
            name='structure_provenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cas', to='epidemie.servicesanitaire'),
        ),
    ]
