# Generated by Django 4.2.15 on 2024-09-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0035_alter_cassynthese_structure_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cassynthese',
            name='structure_provenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cas', to='epidemie.servicesanitaire'),
        ),
        migrations.CreateModel(
            name='SyntheseDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_cas_suspects', models.IntegerField(default=0, help_text='Nombre de cas suspects.')),
                ('cas_positif', models.IntegerField(default=0, help_text='Indique si le cas est positif.')),
                ('cas_negatif', models.IntegerField(default=0, help_text='Indique si le cas est négatif.')),
                ('evacue', models.IntegerField(default=0, help_text='Indique si le cas a été évacué.')),
                ('decede', models.IntegerField(default=0, help_text='Indique si le cas est décédé.')),
                ('gueri', models.IntegerField(default=0, help_text='Indique si le cas est guéri.')),
                ('suivi_en_cours', models.IntegerField(default=0, help_text='Indique si le suivi est en cours.')),
                ('nbre_sujets_contacts', models.IntegerField(default=0, help_text='Nombre de sujets contacts.')),
                ('contacts_en_cours_suivi', models.IntegerField(default=0, help_text='Nombre de contacts en cours de suivi.')),
                ('contacts_sorti_suivi', models.IntegerField(default=0, help_text='Nombre de contacts sortis du suivi.')),
                ('devenu_suspect', models.IntegerField(default=0, help_text='Nombre de contacts devenus suspects.')),
                ('devenu_positif', models.IntegerField(default=0, help_text='Nombre de contacts devenus positifs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district_sanitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syntheses', to='epidemie.districtsanitaire')),
            ],
        ),
    ]
