# Generated by Django 4.2.15 on 2024-09-11 11:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0036_alter_cassynthese_structure_provenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtsanitaire',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
