# Generated by Django 4.2.15 on 2024-09-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0037_districtsanitaire_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtsanitaire',
            name='geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
