# Generated by Django 4.2.15 on 2024-09-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epidemie', '0038_districtsanitaire_geojson'),
    ]

    operations = [
        migrations.AddField(
            model_name='synthesedistrict',
            name='maladie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maladiesdesynthese', to='epidemie.epidemie'),
            preserve_default=False,
        ),
    ]
